function decodeMsg(msg){if(msg==null)return"";var i0=msg.indexOf("[");var i1=msg.indexOf("]");var msgType=msg.substr(1,2);if(i0==0&&i1==3)if(msgType=="00"||msgType=="01"||msgType=="02"||msgType=="03"||msgType=="04"||msgType=="05"||msgType=="06"||msgType=="07"||msgType=="08"||msgType=="09"||msgType=="10")return msg.substr(4);else return msg;else return msg}
function isTextMsg(msg){if(msg==null)return false;var i0=msg.indexOf("[");var i1=msg.indexOf("]");var msgType=msg.substr(1,2);if(i0==0&&i1==3&&msgType=="00")return true;else return false}function isImgMsg(msg){if(msg==null)return false;var i0=msg.indexOf("[");var i1=msg.indexOf("]");var msgType=msg.substr(1,2);if(i0==0&&i1==3&&msgType=="01")return true;else return false}function getRoomIdGroup(threadId){var currentRoomId="";currentRoomId="talk_"+threadId;return currentRoomId}
function getRoomIdP2P(userId,toUserId){var currentRoomId="";if(userId<toUserId)currentRoomId="talk_"+userId+"-"+toUserId;else currentRoomId="talk_"+toUserId+"-"+userId;return currentRoomId}function getToUserIdP2P(currentRoomId,userId){var touid="";if(currentRoomId.indexOf("-")>0){var ids=currentRoomId.split("_")[1].split("-");if(ids[0]==userId)touid=ids[1];else touid=ids[0]}else touid="";return touid}function getRoomMsgCount(roomId){var counts=getstorage(roomId+"_count");return counts}
function getRoomMsgUsers(roomId){var counts=getstorage(roomId+"_users");return counts}
function updateTalkServerUrl(roomId){var currentRoomId_url_key=roomId+"_url";var currentRoomId_url=getstorage(currentRoomId_url_key);if(currentRoomId_url==null||currentRoomId_url==""){var api_url=yh_talk_server+"msg/getChatServer.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="roomId";param2.value=currentRoomId;paramsArray[1]=param2;$.getJSON(api_url,function(data){var ip=
data.ip;var port=data.port;var connUrl="http://"+ip+":"+port;setstorage(currentRoomId_url_key,connUrl)},"json",function(data){alert("\u83b7\u53d6\u804a\u5929\u670d\u52a1\u5668\u5730\u5740\u9519\u8bef\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\u3002")},"POST",paramsArray,false)}}
function updateRoomMsgCount(roomId){var currentRoomId_count_key=roomId+"_count";var api_url=yh_talk_server+"msg/getMsgCount.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="roomId";param2.value=roomId;paramsArray[1]=param2;$.getJSON(api_url,function(data){var count=data.count;var oldcount=getstorage(currentRoomId_count_key);if(oldcount==null||oldcount==""||oldcount==
"0")setstorage(currentRoomId_count_key,count);else{var news=count-oldcount;setstorage(currentRoomId_count_key,news)}},"json",function(data){alert("\u83b7\u53d6\u804a\u5929\u8bb0\u5f55\u6570\u9519\u8bef\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\u3002")},"POST",paramsArray,false)}
function updateRoomUserCount(roomId){var currentRoomId_user_key=roomId+"_users";var api_url=yh_talk_server+"msg/getUserCount.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="roomId";param2.value=roomId;paramsArray[1]=param2;$.getJSON(api_url,function(data){var count=data.count;setstorage(currentRoomId_user_key,count)},"json",function(data){alert("\u83b7\u53d6\u804a\u5929\u7528\u6237\u6570\u9519\u8bef\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\u3002")},
"POST",paramsArray,false)}
function sendAppInfo(appId,userId,mobileType){saveAppInfo();var api_url=yh_talk_server+"msg/sendAppInfo.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="appId";param2.value=appId;paramsArray[1]=param2;var param3={};param3.type="0";param3.key="userId";param3.value=userId;paramsArray[2]=param3;var param4={};param4.type="0";param4.key="mobileType";param4.value=mobileType;
paramsArray[3]=param4;var param5={};param5.type="0";param5.key="mobileParams";param5.value=getstorage("myappinfo");paramsArray[4]=param5;var param6={};param6.type="0";param6.key="other";param6.value="login";paramsArray[5]=param6;$.getJSON(api_url,function(data){},"json",function(data){},"POST",paramsArray,false)}
function sendAppInfoHistory(appId,userId,mobileType){saveAppInfo();var api_url=yh_talk_server+"msg/sendAppInfoHistory.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="appId";param2.value=appId;paramsArray[1]=param2;var param3={};param3.type="0";param3.key="userId";param3.value=userId;paramsArray[2]=param3;var param4={};param4.type="0";param4.key="mobileType";param4.value=
mobileType;paramsArray[3]=param4;var param5={};param5.type="0";param5.key="mobileParams";param5.value=getstorage("myappinfo");paramsArray[4]=param5;var param6={};param6.type="0";param6.key="other";param6.value="init";paramsArray[5]=param6;$.getJSON(api_url,function(data){},"json",function(data){},"POST",paramsArray,false)}
function saveAppInfo(){if(isSML)return;var key_tmp="myappinfo";var value_tmp=getstorage(key_tmp);if(value_tmp==null||value_tmp==""||value_tmp=="null"){var v="";v="SYSTEM_TYPE:"+api.systemType+"@SYSTEM_VERSION:"+api.systemVersion+"@APP_VERSION:"+api.appVersion+"@DEVICE_ID:"+api.deviceId+"@DEVICE_NAME:"+api.deviceName+"@DEVICE_MODEL:"+api.deviceModel+"@NET_TYPE:"+api.connectionType;setstorage(key_tmp,v)}}
function getLatestMsgCountByUserId(){var api_url=yh_talk_server+"msg/getLatestMsgCountByUserId.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="userId";param2.value=getstorage("UID");paramsArray[1]=param2;$.getJSON(api_url,function(data){var pm=data.pm;setstorage("pm",pm)},"json",function(data){},"POST",paramsArray,false)}
function loadMsgListFromStorage(){var currentDataList_str=getstorage("currentDataList_str");if(currentDataList_str!=null&&currentDataList_str!=""){var currentDataList=[];var temps=currentDataList_str.split("@");for(var i=0;i<temps.length;i++){var currentData={};var temp=temps[i].split("#");currentData.isnew=temp[0];currentData.isread=temp[1];currentData.room_id=temp[2];currentData.msg_time=temp[3];currentData.msg_sender=temp[4];currentData.isdeleted=temp[5];currentDataList.push(currentData)}return currentDataList}else return null}
function saveDataListToStarage(currentDataList){var currentDataList_str="";if(currentDataList==null){setstorage("currentDataList_str","");return}var len=currentDataList.length;if(len<1){setstorage("currentDataList_str","");return}if(len==1){currentDataList_str=currentDataList[len-1].isnew+"#"+currentDataList[len-1].isread+"#"+currentDataList[len-1].room_id+"#"+currentDataList[len-1].msg_time+"#"+currentDataList[len-1].msg_sender+"#"+currentDataList[len-1].isdeleted;setstorage("currentDataList_str",
currentDataList_str)}else{for(var i=0;i<len-1;i++){var temp=currentDataList[i].isnew+"#"+currentDataList[i].isread+"#"+currentDataList[i].room_id+"#"+currentDataList[i].msg_time+"#"+currentDataList[i].msg_sender+"#"+currentDataList[i].isdeleted+"@";currentDataList_str=currentDataList_str+temp}currentDataList_str=currentDataList_str+currentDataList[len-1].isnew+"#"+currentDataList[len-1].isread+"#"+currentDataList[len-1].room_id+"#"+currentDataList[len-1].msg_time+"#"+currentDataList[len-1].msg_sender+
"#"+currentDataList[len-1].isdeleted;setstorage("currentDataList_str",currentDataList_str)}}function updatePm(currentDataList){var len=currentDataList.length;var pm=0;for(var i=0;i<len;i++){var isread=currentDataList[i].isread;var isnew=currentDataList[i].isnew;if(isnew==1&&isread==0)pm=pm+1}setstorage("pm",pm)};