var tokenkey="";var qqopenid="";var shareed=0;var cb_url="http://www.3g2win.com/tiaozhuan/index.html";var weibo={};function cbError(opid,errCode,errDes){if(opid=="30"||opid=="31"){uexXmlHttpMgr.close(opid);uexWindow.toast("0","5","\u5206\u4eab\u5931\u8d25",2E3)}}
function weibo_send(key,openid){var type=weibo.type;setstorage(tokenkey,key);if(openid)setstorage(qqopenid,openid);if(weibo.cb){weibo.cb(type);return}var appname=getstorage("appname");var text="\u6765\u81ea"+appname+"\u5ba2\u6237\u7aef   "+weibo.subject+"\u3000"+weibo.content;var cont=encodeURIComponent(text);var url="weibosend.html?key\x3d"+key+"\x26cont\x3d"+cont+"\x26type\x3d"+type+"\x26openid\x3d"+openid+"\x26appkey\x3d"+weibo[type].appkey;logs("weibo_send--\x3eurl\x3d"+url);setstorage("params",
'{"key":"'+key+'", "cont":"'+text+'", "type":"'+type+'", "openid":"'+openid+'", "appkey":"'+weibo[type].appkey+'"}');openwin("weibosend","weibosend.html","2")}
function onOAuth(winNam,url){if(winNam=="webpage"){logs("onOAuth--\x3eurl\x3d"+url);if(weibo.type==1){if(url.indexOf(cb_url)==0){var key=url.match(/(.*)#access_token=(.*)&expires_in=(.*)&uid=(.*)/);if(isDefine(key)){uescript("weibologin","closewin('0');");var k=key[2];var kk=k.split("\x26");if(kk)k=kk[0];weibo_send(k);logs("sina weibo key1\x3d"+key[2]+", key2\x3d"+k)}else uescript("weibologin","closewin();")}}else if(weibo.type==0){var key=url.match(/(.*)#access_token=(.*)&expires_in=(.*)&openid=(.*)&openkey=(.*)/);
if(isDefine(key)){logs("qq weibo key\x3d"+key[2]);weibo[0].openid=key[4];weibo_send(key[2],key[4]);uescript("weibologin","closewin('0');")}}else{var key=url.match(/(.*)#access_token=(.*)&expires_in=(.*)&refresh_token=(.*)/);if(isDefine(key)){logs("163_weibo_key \x3d "+key[2]);weibo_send(key[2]);uescript("weibologin","closewin('0');")}}}}
function sharestart(cont,uid,sub,wname){logs("sharestart(cont, uid, wname): uid\x3d"+uid+", wname\x3d"+wname);weibo.content=cont;weibo.subject=sub;weibo.uid=uid;weibo.wname=wname;uexWidgetOne.cbError=cbError;setstorage("key_0_2","");uexWindow.cbActionSheet=function(opId,dataType,data){logs("cbActionSheet--\x3edata\x3d"+data);var d=parseInt(data);if(d<3)weibo_open(d)};var array=["\u817e\u8baf\u5fae\u535a","\u65b0\u6d6a\u5fae\u535a","\u7f51\u6613\u5fae\u535a"];uexWindow.actionSheet("","\u53d6\u6d88",
array)}
function weibo_open(type,uid,cb,wname){var appkey="";var cburl="";var url="";weibo.type=type;weibo.cb=cb;if(uid)weibo.uid=uid;if(wname)weibo.wname=wname;logs("weibo_open(type, uid, cb, wname)--\x3etype\x3d"+type+", uid\x3d"+uid+", wname\x3d"+wname);if(!weibo[type])if(type==0){weibo[type]={appkey:"801088600",shareed:0};qqopenid="opid_"+weibo.uid}else if(type==1)weibo[type]={appkey:"3845409824",shareed:0};else if(type==2)weibo[type]={appkey:"0PU25xVLBJ2ChzPF",shareed:0};if(weibo[type].shareed==1){uexWindow.toast("0",
"5","\u5df2\u5206\u4eab\u5230\u5fae\u535a",2E3);return}var obj=getStorJson("usetting");var wbk=weibo[type].appkey;if(type==1){if(obj.weibo_sina&&obj.weibo_sina_callback){wbk=obj.weibo_sina;cb_url=obj.weibo_sina_callback}}else if(type==0){if(obj.weibo_tencent&&obj.weibo_tencent_callback){wbk=obj.weibo_tencent;cb_url=obj.weibo_tencent_callback}}else;weibo[type].appkey=wbk;tokenkey="key_"+weibo.uid+"_"+type;var token=getstorage(tokenkey);logs("share.js--\x3egetstorage--\x3etokenkey\x3d"+tokenkey+", token\x3d"+
token);if(isDefine(token)){var qqopid="";if(type==0)qqopid=getstorage(qqopenid);weibo_send(token,qqopid);return}appkey=encodeURIComponent(wbk);cburl=encodeURIComponent(cb_url);logs("wdopen--\x3eweibologin.html");setstorage("params",'{"key":"'+appkey+'", "url":"'+cburl+'", "type":"'+type+'", "wname":"'+weibo.wname+'"}');openwin("weibologin","weibologin.html","2")}
function delweibo(t,tk){if(t==1){var wb_if="https://api.weibo.com/2/account/end_session.json";uexXmlHttpMgr.open("50","GET",wb_if+"?access_token\x3d"+tk,"60000");uexXmlHttpMgr.send("50")}}var weibop=getStorJson("params");
function weiboSubmit(txt,src){logs("weiboSubmit()--\x3etxt\x3d"+txt);var key=weibop.key;var type=weibop.type;var wb_if="";var str="";var picUrl=src;var text=txt;weibop.txt=txt;var len=fucCheckLength(text);logs("len\x3d"+len);if(len>140){uexWindow.toast("0","5","\u5206\u4eab\u5185\u5bb9\u8bf7\u5c0f\u4e8e140\u4e2a\u5b57",2E3);return}if(type==1){wb_if="https://api.weibo.com/2/statuses/update.json?";if(isDefine(picUrl))wb_if="https://api.weibo.com/2/statuses/upload.json?";str="\u65b0\u6d6a"}else if(type==
0){var ip="127.0.0.1";var url="t/add?";if(isDefine(picUrl))url="t/add_pic?";var rurl="https://open.t.qq.com/api/"+url;rurl+="\x26scope\x3dall\x26format\x3djson";rurl+="\x26clientip\x3d"+ip;rurl+="\x26oauth_version\x3d2.a";rurl+="\x26openid\x3d"+weibop.openid;rurl+="\x26oauth_consumer_key\x3d"+weibop.appkey+"\x26";wb_if=rurl;str="\u817e\u8baf"}else{wb_if="https://api.t.163.com/statuses/update.json?";if(isDefine(picUrl))wb_if="https://api.t.163.com/statuses/upload.json?pic"+picUrl+"\x26";str="\u7f51\u6613"}uexWindow.toast("1",
"5","\u6b63\u5728\u5206\u4eab\u81f3"+str+"\u5fae\u535a","");uexXmlHttpMgr.onData=weiboCb;uexWidgetOne.cbError=cbError;logs("weibo_send--\x3eurl\x3d"+wb_if);uexXmlHttpMgr.open("30","POST",wb_if,"60000");uexXmlHttpMgr.setPostData("30","0","access_token",key);if(isDefine(picUrl))uexXmlHttpMgr.setPostData("30","1","pic",picUrl);if(weibop.upload_image_url){uexXmlHttpMgr.setPostData("30","1","upload_image_url",weibop.upload_image_url);logs("weibo_send--\x3esetPostData--\x3eupload_image_url\x3d"+weibop.upload_image_url);
weibop.upload_image_url=""}if(type==0)uexXmlHttpMgr.setPostData("30","0","content",text);else uexXmlHttpMgr.setPostData("30","0","status",text);uexXmlHttpMgr.send("30")}function cbError(opid,errCode,errDes){if(opid=="30"||opid=="31"){uexXmlHttpMgr.close(opid);uexWindow.toast("0","5","\u5206\u4eab\u5931\u8d25",2E3)}}
function weiboCb(opId,status,data){logs("weiboCb--\x3eopId\x3d"+opId+", status\x3d"+status+", data111\x3d"+data);if(Int(opId)==30){var type=weibop.type;if(Int(status)==1){uexXmlHttpMgr.close(opId);if(type==1){var json=JSON.parse(data);if(isDefine(json.created_at))uexWindow.toast("0","5","\u5206\u4eab\u5230\u65b0\u6d6a\u5fae\u535a\u6210\u529f",2E3);else if(json.error_code==21327)openwin("login","login.html","12");else if(json.error_code==20019)uexWindow.toast("0","5","\u4f60\u5df2\u7ecf\u5206\u4eab\u8fc7\u4e00\u6b21\uff0c\u4e0d\u80fd\u91cd\u590d\u5206\u4eab",
2E3);else uexWindow.toast("0","5","\u5206\u4eab\u5230\u65b0\u6d6a\u5fae\u535a\u5931\u8d25",2E3)}else if(type==0){var json=JSON.parse(data);var str="\u5206\u4eab\u5230\u817e\u8baf\u5fae\u535a\u5931\u8d25";if(json.ret==0)str="\u5206\u4eab\u5230\u817e\u8baf\u5fae\u535a\u6210\u529f";uexWindow.toast("0","5",str,2E3)}else{var json=JSON.parse(data);if(json&&json.upload_image_url){weibop.upload_image_url=json.upload_image_url;weiboSubmit(weibop.txt);return}var str="\u5206\u4eab\u5230\u7f51\u6613\u5fae\u535a\u5931\u8d25";
if(json.created_at)str="\u5206\u4eab\u5230\u7f51\u6613\u5fae\u535a\u6210\u529f";uexWindow.toast("0","5",str,2E3)}setTimeout("uescript('weibosend','closewin();');",1500)}else{var note="\u5df2\u5206\u4eab\u5230\u65b0\u6d6a\u5fae\u535a";if(type==1){if(data=="error:403")note="\u5206\u4eab\u5931\u8d25\uff01access_token\u9519\u8bef\u3002";uexXmlHttpMgr.close(opId)}uexWindow.toast("0","5",note,2E3)}}};