var isPhone=window.navigator.platform!="Win32";var isAndroid=window.navigator.userAgent.indexOf("Android")>=0?true:false;var isiPhone=window.navigator.userAgent.indexOf("iPhone")>=0?true:false;var isiPad=window.navigator.userAgent.indexOf("iPad")>=0?true:false;
function getSoftToken(appId,userId){var key=""+appId+"-"+userId;var value=getLocVal(key);if(value.length>1)return"\u7f13\u5b58\u91cc\u5df2\u6709"+value;var url="";if(isiPhone)url="http://newpush.appcan.cn/msg/listUserPage1?platform\x3d0\x26appId\x3d"+appId+"\x26search\x3d"+userId+"\x26pageNo\x3d\x26pageSize\x3d\x26next\x3d1\x26pre\x3d-1";else url="http://newpush.appcan.cn/msg/listUserPage1?platform\x3d1\x26appId\x3d"+appId+"\x26search\x3d"+userId+"\x26pageNo\x3d\x26pageSize\x3d\x26next\x3d1\x26pre\x3d-1";
var softToken=[];var key=""+appId+"-"+userId;$.getJSON(url,function(data){var userList=[];userList=data.userList;if(userList!=null&&userList.length>0){for(var i=0;i<userList.length;i++)softToken[i]=userList[i].softToken;setLocVal(key,softToken.join(","))}else setLocVal(key,"none");alert("ajax\u5df2\u53d6\u5230"+getLocVal(key))},"json",function(e){setLocVal(key,"")},"GET","",false)}
function sendMsgToAllUser(appId,msgName,content,key,value){var paramsArray=[];var param1={};param1.type="0";param1.key="appId";param1.value=appId;paramsArray.push(param1);var param2={};param2.type="0";param2.key="platforms";if(isiPhone)param2.value="0";else param2.value="1";paramsArray.push(param2);var param3={};param3.type="0";param3.key="msgName";param3.value=msgName;paramsArray.push(param3);var param4={};param4.type="0";param4.key="title";param4.value=content;paramsArray.push(param4);var param5=
{};param5.type="0";param5.key="body";param5.value='{"'+key+'":"'+value+'","msgName":"'+msgName+'"}';paramsArray.push(param5);var param6={};param6.type="0";param6.key="badgeNum";param6.value="";paramsArray.push(param6);var param7={};param7.type="0";param7.key="pushTime";param7.value="";paramsArray.push(param7);var param8={};param8.type="0";param8.key="keepHours";param8.value="24";paramsArray.push(param8);var param9={};param9.type="0";param9.key="save";param9.value="2";paramsArray.push(param9);var param10=
{};param10.type="0";param10.key="userScope";param10.value="1";paramsArray.push(param10);var param11={};param11.type="0";param11.key="keys";param11.value=key;paramsArray.push(param11);var param12={};param12.type="0";param12.key="values";param12.value=value;paramsArray.push(param12);var sendStatus=false;var url="http://newpush.appcan.cn/msg/pushMsg";$.getJSON(url,function(data){if(data.status=="ok"){sendStatus=true;uexWindow.closeToast();uexWindow.toast("0","5","\u63a8\u9001\u6210\u529f",5E3)}else{uexWindow.closeToast();
uexWindow.toast("0","5","\u63a8\u9001\u5931\u8d25",5E3)}},"json",function(e){uexWindow.closeToast();uexWindow.toast("0","5","\u63a8\u9001\u5931\u8d25\uff0c\u7f51\u7edc\u9519\u8bef",2E3)},"POST",paramsArray,false);return sendStatus}
function sendMsgToUser(appId,userId,msgName,content,key,value){var key_token=""+appId+"-"+userId;var softToken_str=getLocVal(key_token);var sendStatus=false;if(softToken_str!="none"||softToken_str!=""){softToken_str=getLocVal(key_token);var softToken=softToken_str.split(",");for(var i=0;i<softToken.length;i++)if(softToken[i].length>1&&softToken[i]!="none")sendStatus=sendMsgToUserBySoftToken(appId,softToken[i],msgName,content,key,value)}return sendStatus}
function sendMsgToUserBySoftToken(appId,softToken,msgName,content,key,value){var paramsArray=[];var param1={};param1.type="0";param1.key="appId";param1.value=appId;paramsArray.push(param1);var param2={};param2.type="0";param2.key="platforms";if(isiPhone)param2.value="0";else param2.value="1";paramsArray.push(param2);var param3={};param3.type="0";param3.key="msgName";param3.value=msgName;paramsArray.push(param3);var param4={};param4.type="0";param4.key="title";param4.value=content;paramsArray.push(param4);
var param5={};param5.type="0";param5.key="body";param5.value='{"'+key+'":"'+value+'","msgName":"'+msgName+'"}';paramsArray.push(param5);var param6={};param6.type="0";param6.key="badgeNum";param6.value="";paramsArray.push(param6);var param7={};param7.type="0";param7.key="pushTime";param7.value="";paramsArray.push(param7);var param8={};param8.type="0";param8.key="keepHours";param8.value="24";paramsArray.push(param8);var param9={};param9.type="0";param9.key="save";param9.value="2";paramsArray.push(param9);
var param10={};param10.type="0";param10.key="userScope";param10.value="0";paramsArray.push(param10);var param11={};param11.type="0";param11.key="keys";param11.value=key;paramsArray.push(param11);var param12={};param12.type="0";param12.key="values";param12.value=value;paramsArray.push(param12);var param13={};param13.type="0";param13.key="softToken";param13.value=softToken;paramsArray.push(param13);var url="http://newpush.appcan.cn/msg/pushMsg";var sendStatus=false;$.getJSON(url,function(data){if(data.status==
"ok"){sendStatus=true;uexWindow.closeToast();uexWindow.toast("0","5","\u63a8\u9001\u6210\u529f",5E3)}else{uexWindow.closeToast();uexWindow.toast("0","5","\u63a8\u9001\u5931\u8d25",5E3)}},"json",function(e){uexWindow.closeToast();uexWindow.toast("0","5","\u63a8\u9001\u5931\u8d25\uff0c\u7f51\u7edc\u9519\u8bef",2E3)},"POST",paramsArray,false);return sendStatus};