function loadprofile(tid,fg){var url=forum_url+"\x26mod\x3dajax\x26action\x3dgetprofile\x26tid\x3d"+tid;logs("forum--\x3eurl\x3d"+url);if(!checkKey(url))uexWindow.toast("1","5","\u52a0\u8f7d\u4e2d...","");$.getJSON(url,loadprofileCb,"json",getJsonErr,"POST","",fg,"1")}
function loadprofileCb(json){uexWindow.closeToast();if(json){var content="";var title="",tmpl="",single=false;if(!isUndefined(o_single))if(o_single=="true")single=true;if($$("cb"))$$("cb").checked=single;htmls=json.htmls;for(var key in htmls){var value=htmls[key];title=value["title"];content=value["content"];if(key=="mobile")content=' \x3cdiv class\x3d"uinput ub-f1 ub sel"\x3e'+'\x3cinput type\x3d"text" name \x3d"'+key+'"  id\x3d"'+key+'" class\x3d"ulev-1 tx-r t-gra1" style\x3d"padding:0" value\x3d"'+
content+'" readonly\x3d"true" onclick \x3d"go2mobiles();"\x3e'+'\x3cdiv class\x3d"b-gra2 ubb"\x3e\x3c/div\x3e'+"\x3c/div\x3e";tmpl+='\x3cdiv ontouchstart\x3d"zy_touch(\'btn-act\')" class\x3d"uc-t ub ubb b-gra ub-ac lis umh4"\x3e'+'\x3cdiv class\x3d"ub tx-r t-gra ulev-3 ub-f1"\x3e'+'\x3cdiv class\x3d"ub ub-pa uinn4 p_title"\x3e'+title+"\x3c/div\x3e"+content+"\x3c/div\x3e"+"\x3c/div\x3e"}setHtml("profilebox",tmpl);zy_anim_pop("wrap","uhide");if(json.verify_status){var verify=json.verify_status;if(verify==
"0")if(!verifying)setHtml("verify_status","\u672a\u9a8c\u8bc1");else setHtml("verify_status","\u9a8c\u8bc1\u4e2d\uff0c\u8bf7\u90ae\u4ef6\u6fc0\u6d3b");if(verify=="1")setHtml("verify_status","\u5df2\u9a8c\u8bc1");var email=json.email;var company=json.company;setStorJson("params",{"email":email,"company":company,"wn":"manage_role","pop":"content"})}addEvent();setselectindex()}}
function addEvent(){var key,value,obj;var fields=["company"];for(key in fields){value=fields[key];obj=$$(value);if(obj){obj.onclick=function(){profile_suggest(this.id,this.value)};$$(value).setAttribute("readonly","readonly")}}}function profile_suggest(field,value){$$(field).style.border="none !important;";setStorJson("params",{field:field,value:value,from_wnd:"activity_join",from_frame:"content"});openwin("suggest","manage_roleedit_suggest.html",10)}
function set_suggest_field(field,value){console.log(field+"::"+value);var obj=$$(field);if(!obj||!value)return;obj.value=value}
function checkinput(){var formobj=document.getElementById("postform");for(var i=0;i<formobj.elements.length;i++){var obj=formobj.elements[i];if(obj.type!="hidden"&&obj.type!="button"&&obj.tagName!="BUTTON"&&(obj.value==""||obj.value=="0")){obj.style.border="1px solid";obj.focus();uexWindow.toast("0","5","\u8bf7\u8f93\u5165\u4fe1\u606f",2E3);return false}else if(obj.tagName=="SELECT"){var sp=obj.parentElement;if(!sp)return false;var ch=sp.getElementsByTagName("div")[0];if(ch&&ch.innerHTML==""){ch.style.border=
"1px solid";uexWindow.toast("0","5","\u8bf7\u9009\u62e9",2E3);return false}}else if(obj.id=="mobile")return checkMobile()}return true}function checkMobile(){var mobile=getValue("mobile");var re=/1(?:[38]\d|4[57]|5[01256789])\d{8}/;if(!re.test(mobile)){uexWindow.toast("0","5","\u624b\u673a\u53f7\u7801\u4e0d\u6b63\u786e",1500);return false}return true}function showbirthday(){}
function selectmenu(id){var sl=document.getElementById(id);if(sl){var sp=sl.parentElement;if(sp){var ch=sp.getElementsByTagName("div")[0];var si=sl.selectedIndex;var t=sl.options[si].text;if(ch){ch.innerHTML=t;ch.className="ub-f1 ut-s ulev-1 t-gra1 tx-r"}}}}
function clickmenu(id){var sl=document.getElementById(id);sl.style.border="";var sp=sl.parentElement;if(!sp)return;var ch=sp.getElementsByTagName("div")[0];var si=sl.selectedIndex;var t=sl.options[si].text;if(!ch||ch.innerHTML!="")return;ch.style.border="none !important;";switch(id){case "gender":ch.innerHTML=t;break;case "birthyear":ch.innerHTML="1985";break;case "height":ch.innerHTML="170";break;case "education":ch.innerHTML="\u672c\u79d1";break;case "resideprovince":ch.innerHTML="\u4e0a\u6d77\u5e02";
break;case "occupation":ch.innerHTML=t;break;case "graduateschool":ch.innerHTML=t;break;case "major":ch.innerHTML=t;break;case "schoolyear":ch.innerHTML="2003";break}}
function setselectindex(){var fields=["birthyear","height","education","resideprovince","schoolyear"];var id;for(key in fields){id=fields[key];var sl=document.getElementById(id);if(!sl)continue;var sp=sl.parentElement;if(!sp)continue;var ch=sp.getElementsByTagName("div")[0];var si=sl.selectedIndex;var t=sl.options[si].text;if(!ch||ch.innerHTML!="")continue;switch(id){case "birthyear":sl.selectedIndex=parseInt(t)-parseInt("1985");break;case "height":sl.selectedIndex=parseInt("170")-parseInt(t);break;
case "education":sl.selectedIndex=2;break;case "resideprovince":sl.selectedIndex=8;break;case "schoolyear":sl.selectedIndex=parseInt(t)-parseInt("2003");break}}};