Date.prototype.format=function(fmt){var year=this.getFullYear();var month=this.getMonth()+1;var date=this.getDate();var hour=this.getHours();var minute=this.getMinutes();var second=this.getSeconds();fmt=fmt.replace("yyyy",year);fmt=fmt.replace("yy",year%100);fmt=fmt.replace("MM",fix(month));fmt=fmt.replace("dd",fix(this.getDate()));fmt=fmt.replace("hh",fix(this.getHours()));fmt=fmt.replace("mm",fix(this.getMinutes()));fmt=fmt.replace("ss",fix(this.getSeconds()));return fmt;function fix(n){return n<
10?"0"+n:n}};var currentUserId=getstorage("UID");var currentRoomId=getstorage("currentRoomId");var currentMsgCount=10;var currentMsgCount_end=-1;var currentFactMsgCount=0;var pageStart=0;var pageSize=20;var pageCount=0;var currentRoomId_url_key="";var cansendmsg=false;function showTopNMsg(msg){if(msg==undefined)return;printMsgDiv("topN",msg);showUserImage(msg)}function showHistoryMsg(msg){resetBV(0);if(msg==undefined)return;printMsgDiv("history",msg);showUserImage(msg)}var news_msgId=0;
function showMsg(msg){if(msg==undefined)return;if(!msg.msgId){news_msgId++;msg.msgId="news_msgId_"+news_msgId}printMsgDiv("news",msg);showUserImage(msg)}
function sendMsg(){if(cansendmsg==false)return;try{var msg=getstorage("msg");var param={};param.data=msg;YHChatTmp.sendMsg(param,cbOnMsg);uexLog.sendLog("android:sendMsg:"+msg);var msg_fact="";if(isTextMsg(msg))msg_fact=decodeMsg(msg);else if(isImgMsg(msg))msg_fact="\u53d1\u9001\u4e86\u4e00\u5f20\u56fe\u7247\u3002";else msg_fact=msg;if(currentRoomId.indexOf("-")>0){var touid=getToUserIdP2P(currentRoomId,currentUserId);if(touid!=""){var url=home_url+"\x26mod\x3dspacecp\x26ac\x3dpm\x26op\x3dsend\x26touid\x3d"+
touid+"\x26pmsubmit\x3dture\x26message\x3d"+msg_fact;$.getJSON(url,submitCb,"json",getJsonErr,"POST","","")}}else{var pid="";var tid="";if(currentRoomId.indexOf("_")>0)tid=currentRoomId.split("_")[1];var log="";var lat="";var mfr="";var url=forum_url+"\x26mod\x3dpost\x26action\x3dreply\x26tid\x3d"+tid+"\x26pid\x3d"+pid+"\x26replysubmit\x3d1\x26no_notify\x3d1\x26message\x3d"+msg_fact+"\x26special\x3d1"+"\x26longitude\x3d"+log+"\x26latitude\x3d"+lat+"\x26device\x3d"+mfr;$.getJSON(url,submitCb,"json",
getJsonErr,"POST","","")}}catch(e){alert("\u975e\u5e38\u62b1\u6b49\uff0c\u53d1\u9001\u6d88\u606f\u5931\u8d25\uff0c\u8bf7\u91cd\u65b0\u64cd\u4f5c\u3002")}}function submitCb(data){}function getJsonErr(data){}
function getHistoryMsgFromDB(){var api_url=yh_talk_server+"msg/getMsgList.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="roomId";param2.value=currentRoomId;paramsArray[1]=param2;var param3={};param3.type="0";param3.key="pageSize";param3.value=pageSize;paramsArray[2]=param3;var param4={};param4.type="0";param4.key="pageStart";param4.value=pageStart;paramsArray[3]=param4;
$.getJSON(api_url,function(obj){var data=obj.data;resetBV(0);if(data.length==0)$$("allMsg").style.display="none";var msg_temp=data.split("@");if(msg_temp!=null&&msg_temp!=""){pageCount=pageCount+1;pageStart=pageStart+pageCount*pageSize;if(msg_temp.length<10)$$("allMsg").style.display="none";for(var i=0;i<msg_temp.length-1;i++){var msg_one=msg_temp[i].split("\x26");var msg_json={};msg_json.userId=msg_one[2];msg_json.data=msg_one[3];msg_json.time=msg_one[1];msg_json.msgId=msg_one[0];msg_json.userName=
msg_one[4];showHistoryMsg(msg_json)}}},"json",function(data){alert("\u83b7\u53d6\u6d88\u606f\u9519\u8bef\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\u3002")},"POST",paramsArray,false)}
function getChatServer(){currentRoomId=getstorage("currentRoomId");currentRoomId_url_key=currentRoomId+"_url";var connUrl=getstorage(currentRoomId_url_key);if(connUrl!=null&&connUrl!="")initTalk(connUrl);else{var api_url=yh_talk_server+"msg/getChatServer.do";var paramsArray=[];var param1={};param1.type="0";param1.key="key";param1.value="c4ca4238a0b923820dcc509a6f75849b";paramsArray[0]=param1;var param2={};param2.type="0";param2.key="roomId";param2.value=currentRoomId;paramsArray[1]=param2;$.getJSON(api_url,
successCB,"json",errorCB,"POST",paramsArray,false)}}function successCB(dataAjax){var ip=dataAjax.ip;var port=dataAjax.port;if(ip!=""){var connUrl="http://"+ip+":"+port;currentRoomId_url_key=currentRoomId+"_url";setstorage(currentRoomId_url_key,connUrl);initTalk(connUrl)}}function errorCB(dataAjax){alert("\u8fde\u63a5\u5931\u8d25\uff0c\u8bf7\u91cd\u65b0\u6253\u5f00\u9875\u9762\u3002")}
function initTalk(url_t){try{var param={};param.url=url_t;param.roomId=currentRoomId;param.userId=currentUserId;param.count=currentMsgCount;YHChatTmp.init(param,cbOnMsg)}catch(e){uexLog.sendLog("\u8c03\u7528android\u63d2\u4ef6\u65e0\u6548\u679c\u5440\uff1f\uff1f\uff1f")}}
function cbOnMsg(data,err){isconnect=true;cansendmsg=true;uexWindow.closeToast();var data_json=eval("("+data+")");var event=data_json.event;if(event=="init")uexLog.sendLog("[apicloud]\u804a\u5929\u670d\u52a1\u5668\u8fde\u63a5\u6210\u529f"+(new Date).format("yyyy\u5e74MM\u6708dd\u65e5 hh:mm:ss"));else if(event=="error"){cansendmsg=false;uexLog.sendLog("[apicloud]\u804a\u5929\u670d\u52a1\u5668\u8fde\u63a5\u5931\u8d25"+(new Date).format("yyyy\u5e74MM\u6708dd\u65e5 hh:mm:ss"))}else if(event=="sendMsg")uexLog.sendLog("[apicloud]\u53d1\u9001\u6d88\u606f\u6210\u529f"+
(new Date).format("yyyy\u5e74MM\u6708dd\u65e5 hh:mm:ss"));else{uexLog.sendLog("\u4ece\u63d2\u4ef6\u4e2d\u53d6\u5230\u7684\u6d88\u606f"+data);if(data.length>0)if(data_json.event=="news"){var obj={};obj.userId=data_json.userId;obj.data=data_json.data;obj.time=data_json.time;obj.msgId=data_json.msgId;obj.userName=data_json.userName;if(!checkMsgExist(obj.msgId))showMsg(obj)}else{uexLog.sendLog("\u670d\u52a1\u7aef\u63a8\u9001\u5386\u53f2\u6d88\u606f:"+(new Date).format("yyyy\u5e74MM\u6708dd\u65e5 hh:mm:ss"));
var msg_temp=data_json.data.split("@");if(msg_temp!=null&&msg_temp!=""){currentFactMsgCount=msg_temp.length-1;for(var i=0;i<msg_temp.length-1;i++){var msg_one=msg_temp[i].split("\x26");var msg_json={};msg_json.userId=msg_one[2];msg_json.data=msg_one[3];msg_json.time=msg_one[1];msg_json.msgId=msg_one[0];msg_json.userName=msg_one[4];if(!checkMsgExist(msg_json.msgId))showTopNMsg(msg_json)}}}}}
function printMsgDiv(domId,msgObj){var console_msg=document.getElementById(domId);var innerHTML="";var li=document.createElement("li");li.id="li"+msgObj.msgId;li.style="padding-top:0.5em";var data_new="";if(isTextMsg(msgObj.data)){var msg_fact=decodeMsg(msgObj.data);data_new=transText_chat(msg_fact)}else if(isImgMsg(msgObj.data)){var msg_fact=decodeMsg(msgObj.data);var api_url=yh_talk_server+"img/getById.do?key\x3dc4ca4238a0b923820dcc509a6f75849b\x26size\x3d080100\x26id\x3d"+msg_fact;data_new='\x3cimg src\x3d"'+
api_url+'" onclick\x3d"showLargeImg(\''+msg_fact+"');\"/\x3e"}else data_new=decodeMsg(msgObj.data);if(msgObj.userId==currentUserId)if(currentRoomId.indexOf("-")>0)innerHTML='\x3cdiv class\x3d"uc-n"\x3e \x3cdiv ontouchstart\x3d"zy_touch(\'c-gra\')"  class\x3d"ub t-bla ub-at lis ub-rev ub-pe"\x3e\x3cdiv class\x3d"lis-th2 ub-img uc-a1"\x3e\x3cimg src\x3d""  onclick\x3d"msg_menu('+msgObj.userId+');" class\x3d"inforpic" id\x3d"img'+msgObj.msgId+'"\x3e\x3c/div\x3e\x3cdiv class\x3d"ub-f1 ub"\x3e \x3cdiv class\x3d"ub ub-ver"\x3e  \x3cdiv\x3e\x3cdiv style\x3d"margin:0;word-break:break-all;" class\x3d"ui-li-desc ext-txt-color ext-bg-send_my ulev0 uof "\x3e'+
data_new+'\x3c/div\x3e\x3cdiv class\x3d"ext-bg-send-j"\x3e\x3cimg src\x3d"images/sender-j-.png"\x3e\x3c/div\x3e\x3c/div\x3e  \x3cdiv\x3e\x3cdiv class\x3d"ulev-1 ufr uhide" style\x3d"margin-right:1em;"\x3e'+msgObj.userName+'\x3c/div\x3e\x3c/div\x3e \x3c/div\x3e   \x3cdiv class\x3d"ub-f1"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv style\x3d"width:2em;"\x3e\x3c/div\x3e \x3c/div\x3e \x3c/div\x3e';else innerHTML='\x3cdiv class\x3d"uc-n"\x3e \x3cdiv ontouchstart\x3d"zy_touch(\'c-gra\')"  class\x3d"ub t-bla ub-at lis ub-rev ub-pe"\x3e\x3cdiv class\x3d"lis-th2 ub-img uc-a1"\x3e\x3cimg src\x3d""  onclick\x3d"msg_menu('+
msgObj.userId+');" class\x3d"inforpic" id\x3d"img'+msgObj.msgId+'"\x3e\x3c/div\x3e\x3cdiv class\x3d"ub-f1 ub"\x3e \x3cdiv class\x3d"ub ub-ver"\x3e  \x3cdiv\x3e\x3cdiv style\x3d"margin:0;word-break:break-all;" class\x3d"ui-li-desc ext-txt-color ext-bg-send_my ulev0 uof "\x3e'+data_new+'\x3c/div\x3e\x3cdiv class\x3d"ext-bg-send-j"\x3e\x3cimg src\x3d"images/sender-j-.png"\x3e\x3c/div\x3e\x3c/div\x3e  \x3cdiv\x3e\x3cdiv class\x3d"ulev-1 ufr" style\x3d"margin-right:1em;"\x3e'+msgObj.userName+'\x3c/div\x3e\x3c/div\x3e \x3c/div\x3e   \x3cdiv class\x3d"ub-f1"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv style\x3d"width:2em;"\x3e\x3c/div\x3e \x3c/div\x3e \x3c/div\x3e';
else if(currentRoomId.indexOf("-")>0)innerHTML='\x3cdiv class\x3d"uc-n"\x3e \x3cdiv ontouchstart\x3d"zy_touch(\'c-gra\')"  class\x3d"ub t-bla ub-at lis "\x3e\x3cdiv class\x3d"lis-th2 ub-img uc-a1"\x3e\x3cimg src\x3d""  onclick\x3d"msg_menu('+msgObj.userId+');" class\x3d"inforpic" id\x3d"img'+msgObj.msgId+'"\x3e\x3c/div\x3e\x3cdiv class\x3d"ub-f1 ub"\x3e \x3cdiv class\x3d"ub ub-ver"\x3e  \x3cdiv\x3e\x3cdiv class\x3d"ulev-1 ufl uhide" style\x3d"margin-left: 1em;"\x3e'+msgObj.userName+'\x3c/div\x3e\x3c/div\x3e    \x3cdiv\x3e\x3cdiv style\x3d"margin:0;word-break:break-all;" class\x3d"ui-li-desc ext-txt-color ext-bg-send ulev0 uof ext-bg-recv"\x3e'+
data_new+'\x3c/div\x3e\x3cdiv class\x3d"ext-bg-send-j ext-bg-recv-j"\x3e\x3cimg src\x3d"images/recv-j-.png"   \x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e    \x3cdiv class\x3d"ub-f1"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv style\x3d"width:2em;"\x3e\x3c/div\x3e \x3c/div\x3e \x3c/div\x3e';else innerHTML='\x3cdiv class\x3d"uc-n"\x3e \x3cdiv ontouchstart\x3d"zy_touch(\'c-gra\')"  class\x3d"ub t-bla ub-at lis "\x3e\x3cdiv class\x3d"lis-th2 ub-img uc-a1"\x3e\x3cimg src\x3d""  onclick\x3d"msg_menu('+msgObj.userId+
');" class\x3d"inforpic" id\x3d"img'+msgObj.msgId+'"\x3e\x3c/div\x3e\x3cdiv class\x3d"ub-f1 ub"\x3e \x3cdiv class\x3d"ub ub-ver"\x3e  \x3cdiv\x3e\x3cdiv class\x3d"ulev-1 ufl" style\x3d"margin-left: 1em;"\x3e'+msgObj.userName+'\x3c/div\x3e\x3c/div\x3e    \x3cdiv\x3e\x3cdiv style\x3d"margin:0;word-break:break-all;" class\x3d"ui-li-desc ext-txt-color ext-bg-send ulev0 uof ext-bg-recv"\x3e'+data_new+'\x3c/div\x3e\x3cdiv class\x3d"ext-bg-send-j ext-bg-recv-j"\x3e\x3cimg src\x3d"images/recv-j-.png"   \x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e    \x3cdiv class\x3d"ub-f1"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv style\x3d"width:2em;"\x3e\x3c/div\x3e \x3c/div\x3e \x3c/div\x3e';
li.innerHTML=innerHTML;if(domId=="history"){if(console_msg.children.length>0){console_msg.insertBefore(li,console_msg.firstElementChild);try{var msgtimelast=strToDate(getstorage("msgtimelast"));var msgtime=strToDate(msgObj.time);if(DateAfter(msgtime,msgtimelast,5)){var li_time=document.createElement("li");var msgtime_show=showChatDate(msgtime);li_time.innerHTML='\x3cdiv class\x3d"ub ub-pc ub-ac"\x3e\x3cdiv class\x3d"c-gra1 ulev-1 t-wh" style\x3d"padding: 0.1em 0em;"\x3e'+msgtime_show+"\x3c/div\x3e\x3c/div\x3e";
console_msg.insertBefore(li_time,console_msg.firstElementChild)}}catch(e){}}else console_msg.appendChild(li);setstorage("msgtimelast",msgObj.time)}else if(domId=="topN"){try{var msgtime=strToDate(msgObj.time);var msgtimelast;var msgtimelast_str=getstorage("msgtimelast");if(msgtimelast_str==null||msgtimelast_str=="null")msgtimelast=new Date;else msgtimelast=strToDate(msgtimelast_str);if(DateAfter(msgtime,msgtimelast,5)){var li_time=document.createElement("li");var msgtime_show=showChatDate(msgtime);
li_time.innerHTML='\x3cdiv class\x3d"ub ub-pc ub-ac"\x3e\x3cdiv class\x3d"c-gra1 ulev-1 t-wh" style\x3d"padding: 0.1em 0em;"\x3e'+msgtime_show+"\x3c/div\x3e\x3c/div\x3e";console_msg.appendChild(li_time);setstorage("msgtimelast",msgObj.time)}}catch(e){}console_msg.appendChild(li);document.getElementById("msg_end").scrollIntoView()}else{console_msg.appendChild(li);document.getElementById("msg_end").scrollIntoView();updateMsgListWhenNewsCome(msgObj)}}
function showUserImage(msgObj){var userId=msgObj.userId;var msgId=msgObj.msgId;var imgUrl=guc+userId;zy_imgcache("img"+msgId,imgUrl,imgUrl,imgLoadSucSrc,imgLoadErrSrc,null,"jpg")};